Title: "Cosmetic GUI"
noPermissionMessage: "&eYou Dont Have Permission to run the Command"

# a list of aliases to open the cosmetic gui
Aliases: [fakeequip]

# if set to false player having cosmetic armor will drop it on death
# if this line is deleted it defaults to true
keepArmorOnDeath: true



inventoryItems:
  enabledSlotItem:
    Id: lime_stained_glass_pane
    Display: "&aEnabled"
    # if set to true the toggle buttons will have respective armorslot names in there display
    # for example the display name for helmet toggle slot will be "Enabled [HELMET]"
    # this can be useful for non resource pack users
    showToolTip: true
  disabledSlotItem:
    Id: red_stained_glass_pane
    Display: "&cDisabled"
    showToolTip: true
  blockedSlotItem:
    Id: gray_stained_glass_pane
    Display: ""
